version: "3.8"
services:
  aibot:
    build: .
    restart: always
    environment:
      DB_HOST: pg
      DB_USER: postgres
      DB_NAME: postgres
      DB_PASSWORD: ${DB_PASSWORD}
      AI_ROFL_BOT_TOKEN: ${AI_ROFL_BOT_TOKEN}
    networks:
      - dc-net

networks:
  dc-net:
    external: true