ai-rofl-bot:
  token: ${AI_ROFL_BOT_TOKEN}
  owner-id: ${TG_OWNER_ID}
  botLogin: ${AI_ROFL_BOT_LOGIN:AiRoflBot}
gpt:
  token: ${VSE_GPT_TOKEN}
spring:
  application:
    name: aibot
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME:postgres}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      schema: ai-rofl-bot
  flyway:
    enabled: true
    create-schemas: true
    default-schema: ai-rofl-bot
  jpa:
    show-sql: true